[program:__SERVICE_NAME__]
command=__INSTALL_DIR__/scripts/run_proxy_service.sh
directory=__INSTALL_DIR__
autostart=true
autorestart=true
startretries=3
stopasgroup=true
killasgroup=true
stderr_logfile=__LOG_DIR__/__SERVICE_NAME__.err.log
stdout_logfile=__LOG_DIR__/__SERVICE_NAME__.log
environment=PYTHONUNBUFFERED="1"
